/** Tipos de evento en colección timeline */
export const TIMELINE_TYPES = {
  SUPPLIER_CREATED: 'supplier_created',
  SUPPLIER_UPDATED: 'supplier_updated',
  SUPPLIER_IMPORTED: 'supplier_imported',
  SUPPLIER_STATUS_CHANGED: 'supplier_status_changed',
  CONTACT_CREATED: 'contact_created',
  CONTACT_UPDATED: 'contact_updated',
  ACTIVITY_CALL: 'activity_call',
  ACTIVITY_WHATSAPP: 'activity_whatsapp',
  ACTIVITY_MEETING: 'activity_meeting',
  ACTIVITY_VISIT: 'activity_visit',
  ACTIVITY_EMAIL: 'activity_email',
  ACTIVITY_OTHER: 'activity_other',
  OPPORTUNITY_CREATED: 'opportunity_created',
  OPPORTUNITY_UPDATED: 'opportunity_updated',
  OPPORTUNITY_STATUS_CHANGED: 'opportunity_status_changed',
  NOTE_QUICK: 'note_quick',
  VISIT_PHOTO_UPLOADED: 'visit_photo_uploaded',
  VISIT_PHOTO_ASSIGNED: 'visit_photo_assigned',
  VISIT_PHOTO_DELETED: 'visit_photo_deleted',
};

export const TIMELINE_TYPE_LABELS = {
  [TIMELINE_TYPES.SUPPLIER_CREATED]: 'Proveedor creado',
  [TIMELINE_TYPES.SUPPLIER_UPDATED]: 'Proveedor editado',
  [TIMELINE_TYPES.SUPPLIER_IMPORTED]: 'Importación',
  [TIMELINE_TYPES.SUPPLIER_STATUS_CHANGED]: 'Cambio de estado',
  [TIMELINE_TYPES.CONTACT_CREATED]: 'Contacto creado',
  [TIMELINE_TYPES.CONTACT_UPDATED]: 'Contacto editado',
  [TIMELINE_TYPES.ACTIVITY_CALL]: 'Llamada',
  [TIMELINE_TYPES.ACTIVITY_WHATSAPP]: 'WhatsApp',
  [TIMELINE_TYPES.ACTIVITY_MEETING]: 'Reunión',
  [TIMELINE_TYPES.ACTIVITY_VISIT]: 'Visita',
  [TIMELINE_TYPES.ACTIVITY_EMAIL]: 'Email',
  [TIMELINE_TYPES.ACTIVITY_OTHER]: 'Actividad',
  [TIMELINE_TYPES.OPPORTUNITY_CREATED]: 'Oportunidad creada',
  [TIMELINE_TYPES.OPPORTUNITY_UPDATED]: 'Oportunidad editada',
  [TIMELINE_TYPES.OPPORTUNITY_STATUS_CHANGED]: 'Estado oportunidad',
  [TIMELINE_TYPES.NOTE_QUICK]: 'Nota',
  [TIMELINE_TYPES.VISIT_PHOTO_UPLOADED]: 'Foto subida',
  [TIMELINE_TYPES.VISIT_PHOTO_ASSIGNED]: 'Foto asignada',
  [TIMELINE_TYPES.VISIT_PHOTO_DELETED]: 'Foto eliminada',
};

export const TIMELINE_TYPE_ICONS = {
  [TIMELINE_TYPES.SUPPLIER_CREATED]: '◆',
  [TIMELINE_TYPES.SUPPLIER_UPDATED]: '✎',
  [TIMELINE_TYPES.SUPPLIER_IMPORTED]: '⬆',
  [TIMELINE_TYPES.SUPPLIER_STATUS_CHANGED]: '⇄',
  [TIMELINE_TYPES.CONTACT_CREATED]: '◎',
  [TIMELINE_TYPES.CONTACT_UPDATED]: '◎',
  [TIMELINE_TYPES.ACTIVITY_CALL]: '📞',
  [TIMELINE_TYPES.ACTIVITY_WHATSAPP]: '💬',
  [TIMELINE_TYPES.ACTIVITY_MEETING]: '👥',
  [TIMELINE_TYPES.ACTIVITY_VISIT]: '📍',
  [TIMELINE_TYPES.ACTIVITY_EMAIL]: '✉',
  [TIMELINE_TYPES.ACTIVITY_OTHER]: '✎',
  [TIMELINE_TYPES.OPPORTUNITY_CREATED]: '◇',
  [TIMELINE_TYPES.OPPORTUNITY_UPDATED]: '◇',
  [TIMELINE_TYPES.OPPORTUNITY_STATUS_CHANGED]: '◇',
  [TIMELINE_TYPES.NOTE_QUICK]: '📝',
  [TIMELINE_TYPES.VISIT_PHOTO_UPLOADED]: '📷',
  [TIMELINE_TYPES.VISIT_PHOTO_ASSIGNED]: '📷',
  [TIMELINE_TYPES.VISIT_PHOTO_DELETED]: '🗑',
};

export const TIMELINE_FILTER_GROUPS = [
  { value: '', label: 'Todos los tipos' },
  { value: 'supplier', label: 'Proveedor' },
  { value: 'contact', label: 'Contactos' },
  { value: 'activity', label: 'Actividades' },
  { value: 'opportunity', label: 'Oportunidades' },
  { value: 'note', label: 'Notas' },
  { value: 'photo', label: 'Fotos' },
];
